server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:h2:mem:userservice
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # ĐÃ SỬA: Đồng bộ port 8180 và tên Realm "shopping microservices" chuẩn theo link thực tế
          # Sử dụng cấu hình URL của các phiên bản Keycloak mới hiện nay
          issuer-uri: http://localhost:8180/realms/shopping

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

idp:
  # ĐÃ SỬA: Đồng bộ toàn bộ thông tin kết nối với máy chủ Keycloak thực tế của bạn
  url: http://localhost:8180
  client-id: shopping_app
  client-secret: DAxJHo0cBXCcRL28YscseRtMUOomBVrg 
  realm: shopping